name: Terraform Runner

on:
  workflow_dispatch:
    inputs:
      action:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Input
        run: |
          if [[ "${{ github.event.inputs.action }}" != "apply" && "${{ github.event.inputs.action }}" != "destroy" ]]; then
            echo "Invalid action. Use apply or destroy only."
            exit 1
          fi

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ github.event.inputs.project }}
        run: terraform init

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ${{ github.event.inputs.project }}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: ${{ github.event.inputs.project }}
        run: terraform destroy -auto-approve
